# Generated by Django 4.1.3 on 2022-11-23 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0002_layer_berries_available_decor_available_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='delivery_details',
            field=models.TextField(blank=True, default='', verbose_name='Комментарии для курьера'),
        ),
        migrations.AddField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('Preparing', 'Готовится'), ('In delivery', 'Доставляется'), ('Completed', 'Завершен')], default='Preparing', max_length=20, verbose_name='Статус заказа'),
        ),
    ]
