# Generated by Django 4.1.3 on 2022-11-24 08:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0003_order_delivery_details_order_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='last_name',
        ),
        migrations.AlterField(
            model_name='customer',
            name='name',
            field=models.CharField(blank=True, default='', max_length=100, verbose_name='Имя покупателя'),
        ),
        migrations.AlterField(
            model_name='order',
            name='berries',
            field=models.ForeignKey(default='1', on_delete=django.db.models.deletion.SET_DEFAULT, to='database.berries', verbose_name='Ягоды'),
        ),
        migrations.AlterField(
            model_name='order',
            name='decor',
            field=models.ForeignKey(default='1', on_delete=django.db.models.deletion.SET_DEFAULT, to='database.decor', verbose_name='Украшение'),
        ),
        migrations.AlterField(
            model_name='order',
            name='topping',
            field=models.ForeignKey(default='1', on_delete=django.db.models.deletion.SET_DEFAULT, to='database.topping', verbose_name='Топпинг'),
        ),
    ]
