# Generated by Django 4.1.3 on 2022-11-25 16:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0006_alter_order_berries_alter_order_decor_and_more'),
        ('database', '0006_promocode_alter_order_berries_alter_order_decor_and_more'),
    ]

    operations = [
    ]
