# Generated by Django 4.1.3 on 2022-11-25 17:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0007_merge_20221125_1913'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='promocode',
            options={'verbose_name': 'Промокод', 'verbose_name_plural': 'Промокоды'},
        ),
    ]
