# Generated by Django 4.1.3 on 2022-11-27 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0008_alter_promocode_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='feedback',
            field=models.TextField(blank=True, default='', verbose_name='Отзыв о заказе'),
        ),
    ]
