name: Release - Test, Build & Redeploy

on:
  push:
    branches:
      - 'main'

jobs:
  docker:
    name: Publish - Docker Hub
    runs-on: ubuntu-22.04
    steps:
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USER }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - name: Build Docker image
        uses: docker/build-push-action@v2
        with:
          tags: ${{ secrets.DOCKER_REPO }}/cake-site
          context: .
          push: True
