name: Release - Test, Build & Redeploy

on:
  push:
    branches:
      - 'main'

jobs:
  docker:
    name: Publish - Docker Hub
    runs-on: ubuntu-22.04
    steps:
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USER }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - name: Build Docker image
        uses: docker/build-push-action@v3
        with:
          tags: ${{ secrets.DOCKER_REPO }}/cake-site
          push: True
      - name: Redeploy
        uses: appleboy/ssh-action@master
        with:
            host: ${{ secrets.SSH_IP }}
            username: ${{ secrets.SSH_USER }}
            password: ${{ secrets.SSH_PASSWORD }}
            port: ${{ secrets.SSH_PORT }}
            script: |
                docker rm $(docker stop $(docker ps -a -q  --filter ancestor='${{ secrets.DOCKER_REPO }}/cake-site' --format="{{.ID}}"))
                cd ${{ secrets.COMPOSE_PATH }}
                docker-compose pull
                docker-compose up -d